spring.application.name=api-gateway

server.port=8080

spring.main.web-application-type=reactive

# Incident Service
spring.cloud.gateway.server.webflux.routes[0].id=incident-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/incidents/**

# Team Service
spring.cloud.gateway.server.webflux.routes[1].id=team-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/teams/**

# Resource Service
spring.cloud.gateway.server.webflux.routes[2].id=resource-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/resources/**

# Mission Service
spring.cloud.gateway.server.webflux.routes[3].id=mission-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/missions/**

# Alert Service
spring.cloud.gateway.server.webflux.routes[4].id=alert-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/alerts/**